#!/bin/bash
#
### BEGIN INIT INFO
# Provides: openhab-checker
# Required-Start: $syslog
# Required-Stop: $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: Startup/Shutdown openHAB-Checker
### END INIT INFO

case "$1" in
    start)
        # Starting openhab-checker service
        echo -n "Starting openhab-checker service "
        /usr/bin/python /root/openhab-checker.py &
        echo "OK"
        ;;
    status)
        # Checking openhab-checker service status
        echo "Checking openhab-checker service status..."
        PID=$(ps aux | grep 'openhab-checker.py' | grep python | awk '{print $2}')
        if ps aux | grep 'openhab-checker.py' | grep python > /dev/null 2> /dev/null; then
           echo "Service is running"
        else
           echo "Service is not running"
        fi
        ;;
    stop)
        # Shutting down openhab-checker service
        echo -n "Shutting down openhab-checker service"
        kill -9 $(ps aux | grep 'openhab-checker.py' | awk '{print $2}') 2> /dev/null
        echo "OK"
        ;;
    reload|restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 start|stop|restart|status|reload"
        exit 1
esac
exit 0
